# ETL

Comenzaremos importando las librerias y los archivos homicidios.xlsx, de las cuales estan las dos hojas de HECHOS y VICTIMAS

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)#permite ver todas las columnas de un df

## Transformacion del dato

### Importacion de la hoja Hechos

In [9]:
df_accidentes_homicidios = pd.read_excel("Dataset/homicidios.xlsx", sheet_name="HECHOS")
df_accidentes_homicidios.head()

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00  4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00  1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00  7   
3  2016-0004           1 2016-01-10  2016   1  10  00:00:00  0   
4  2016-0005           1 2016-01-21  2016   1  21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             Calle  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  PIEDRA BUENA AV.   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ    PAZ, GRAL. AV.   
2                         AV ENTRE RIOS 2034       AVENIDA    ENTRE RIOS AV.   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA    LARRAZABAL AV.   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA      SAN JUAN AV.   

   Altura                                Cruce  \
0     NaN  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1     NaN                  DE LOS CORRALES AV.   
2  2034.0                                  NaN   
3     NaN             VILLEGAS, CONRADO, GRAL.   
4     NaN              SAENZ PE?A, LUIS, PRES.   

                               Dirección Normalizada  COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...       8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.       9   
2                                ENTRE RIOS AV. 2034       1   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.       8   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.       1   

                                 XY (CABA)         pos x         pos y  \
0    Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1    Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2   Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3    Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4  Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS  
2       MOTO-AUTO    MOTO       AUTO  
3         MOTO-SD    MOTO         SD  
4  MOTO-PASAJEROS    MOTO  PASAJEROS

In [10]:
print("El dataframe hechos tiene filas * columnas: "+ str(df_accidentes_homicidios.shape))

El dataframe hechos tiene filas * columnas: (696, 21)


### Importacion de la hoja VICTIMAS

In [11]:
df_accidentes_homicidios_victimas = pd.read_excel("Dataset/homicidios.xlsx", sheet_name="VICTIMAS")
df_accidentes_homicidios_victimas.head()

ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO   19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO   70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO   30   
3  2016-0004 2016-01-10  2016   1  10  CONDUCTOR    MOTO  MASCULINO   18   
4  2016-0005 2016-01-21  2016   1  21  CONDUCTOR    MOTO  MASCULINO   29   

   FECHA_FALLECIMIENTO  
0  2016-01-01 00:00:00  
1  2016-01-02 00:00:00  
2  2016-01-03 00:00:00  
3                   SD  
4  2016-02-01 00:00:00

In [12]:
print("El dataframe victimas tiene filas * columnas: "+ str(df_accidentes_homicidios_victimas.shape))

El dataframe victimas tiene filas * columnas: (717, 10)


Cambiamos los datos de mayuscula a minuscula

In [13]:
# Convertir los textos de mayuscula a minusculas en : 'ROL', 'VICTIMA', 'SEXO'
df_accidentes_homicidios_victimas['ROL'] = df_accidentes_homicidios_victimas['ROL'].str.lower()
df_accidentes_homicidios_victimas['VICTIMA'] = df_accidentes_homicidios_victimas['VICTIMA'].str.lower()
df_accidentes_homicidios_victimas['SEXO'] = df_accidentes_homicidios_victimas['SEXO'].str.lower()

# Convertir los textos de mayuscula a minusculas en: 'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE' and 6 other columns
df_accidentes_homicidios['LUGAR_DEL_HECHO'] = df_accidentes_homicidios['LUGAR_DEL_HECHO'].str.lower()
df_accidentes_homicidios['TIPO_DE_CALLE'] = df_accidentes_homicidios['TIPO_DE_CALLE'].str.lower()
df_accidentes_homicidios['Calle'] = df_accidentes_homicidios['Calle'].str.lower()
df_accidentes_homicidios['Cruce'] = df_accidentes_homicidios['Cruce'].str.lower()
df_accidentes_homicidios['Dirección Normalizada'] = df_accidentes_homicidios['Dirección Normalizada'].str.lower()
df_accidentes_homicidios['PARTICIPANTES'] = df_accidentes_homicidios['PARTICIPANTES'].str.lower()
df_accidentes_homicidios['VICTIMA'] = df_accidentes_homicidios['VICTIMA'].str.lower()
df_accidentes_homicidios['ACUSADO'] = df_accidentes_homicidios['ACUSADO'].str.lower()

podemos ver que en la columna ROL tenemos datos con ñ y las cambiamos

In [14]:
df_accidentes_homicidios_victimas['ROL'] = df_accidentes_homicidios_victimas['ROL'].str.replace("pasajero_acompañante", "pasajero_acompaniante", case=False, regex=False)

Cambiamos el nombre de la columna 'ID_hecho' a 'idHecho' para poder hacer el merge

In [15]:
# Renombrar la columna
df_accidentes_homicidios_victimas.rename(columns={'ID_hecho': 'idHecho'}, inplace=True)

df_accidentes_homicidios_victimas.head()

idHecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO EDAD  \
0  2016-0001 2016-01-01  2016   1   1  conductor    moto  masculino   19   
1  2016-0002 2016-01-02  2016   1   2  conductor    auto  masculino   70   
2  2016-0003 2016-01-03  2016   1   3  conductor    moto  masculino   30   
3  2016-0004 2016-01-10  2016   1  10  conductor    moto  masculino   18   
4  2016-0005 2016-01-21  2016   1  21  conductor    moto  masculino   29   

   FECHA_FALLECIMIENTO  
0  2016-01-01 00:00:00  
1  2016-01-02 00:00:00  
2  2016-01-03 00:00:00  
3                   SD  
4  2016-02-01 00:00:00

In [16]:
# Rename column 'ID' to 'idHecho'
df_accidentes_homicidios = df_accidentes_homicidios.rename(columns={'ID': 'idHecho'})

Eliminamos columnas que no usaremos en el analisis de nuestros datos

In [17]:
# Drop column: 'PARTICIPANTES'
df_accidentes_homicidios = df_accidentes_homicidios.drop(columns=['PARTICIPANTES'])
# Drop column: 'Altura'
df_accidentes_homicidios = df_accidentes_homicidios.drop(columns=['Altura'])

# Drop column: 'XY (CABA)'
df_accidentes_homicidios = df_accidentes_homicidios.drop(columns=['XY (CABA)'])

Raalizamos el merge entre ambos dataframe

In [18]:
# Realizar un merge basado en la columna 'idHecho'
df_hechos_victimas = pd.merge(df_accidentes_homicidios, df_accidentes_homicidios_victimas, on='idHecho', how='inner') 
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA HH  \
0  2016-0001           1 2016-01-01    2016     1     1  04:00:00  4   
1  2016-0002           1 2016-01-02    2016     1     2  01:15:00  1   
2  2016-0003           1 2016-01-03    2016     1     3  07:00:00  7   
3  2016-0004           1 2016-01-10    2016     1    10  00:00:00  0   
4  2016-0005           1 2016-01-21    2016     1    21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             Calle  \
0  av piedra buena y av fernandez de la cruz       avenida  piedra buena av.   
1          av gral paz  y av de los corrales      gral paz    paz, gral. av.   
2                         av entre rios 2034       avenida    entre rios av.   
3      av larrazabal y gral villegas conrado       avenida    larrazabal av.   
4  av san juan y presidente luis saenz peña        avenida      san juan av.   

                                 Cruce  \
0  fernandez de la cruz, f., gral. av.   
1                  de los corrales av.   
2                                  NaN   
3             villegas, conrado, gral.   
4              saenz pe?a, luis, pres.   

                               Dirección Normalizada  COMUNA         pos x  \
0  piedra buena av. y fernandez de la cruz, f., g...       8  -58.47533969   
1               paz, gral. av. y de los corrales av.       9  -58.50877521   
2                                entre rios av. 2034       1  -58.39040293   
3          larrazabal av. y villegas, conrado, gral.       8  -58.46503904   
4            san juan av. y saenz peã‘a, luis, pres.       1  -58.38718297   

          pos y VICTIMA_x    ACUSADO    FECHA_y  AAAA_y  MM_y  DD_y  \
0  -34.68757022      moto       auto 2016-01-01    2016     1     1   
1  -34.66977709      auto  pasajeros 2016-01-02    2016     1     2   
2  -34.63189362      moto       auto 2016-01-03    2016     1     3   
3  -34.68092974      moto         sd 2016-01-10    2016     1    10   
4  -34.62246630      moto  pasajeros 2016-01-21    2016     1    21   

         ROL VICTIMA_y       SEXO EDAD  FECHA_FALLECIMIENTO  
0  conductor      moto  masculino   19  2016-01-01 00:00:00  
1  conductor      auto  masculino   70  2016-01-02 00:00:00  
2  conductor      moto  masculino   30  2016-01-03 00:00:00  
3  conductor      moto  masculino   18                   SD  
4  conductor      moto  masculino   29  2016-02-01 00:00:00

In [19]:
print("El dataframe unido tiene filas * columnas: "+ str(df_hechos_victimas.shape))

El dataframe unido tiene filas * columnas: (717, 27)


El dataframe tiene la columna N_VICTIMAS la cual ahora todos sus valores deberian ser 1 por la concatenacion

In [20]:
df_hechos_victimas['N_VICTIMAS'] = 1

Eliminamos las columnas de FECHA_y	AAAA_y	MM_y DD_y ya que representan lo mismo

In [21]:
df_hechos_victimas = df_hechos_victimas.drop(['FECHA_y', 'AAAA_y', 'MM_y', 'DD_y', ], axis=1)
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA HH  \
0  2016-0001           1 2016-01-01    2016     1     1  04:00:00  4   
1  2016-0002           1 2016-01-02    2016     1     2  01:15:00  1   
2  2016-0003           1 2016-01-03    2016     1     3  07:00:00  7   
3  2016-0004           1 2016-01-10    2016     1    10  00:00:00  0   
4  2016-0005           1 2016-01-21    2016     1    21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             Calle  \
0  av piedra buena y av fernandez de la cruz       avenida  piedra buena av.   
1          av gral paz  y av de los corrales      gral paz    paz, gral. av.   
2                         av entre rios 2034       avenida    entre rios av.   
3      av larrazabal y gral villegas conrado       avenida    larrazabal av.   
4  av san juan y presidente luis saenz peña        avenida      san juan av.   

                                 Cruce  \
0  fernandez de la cruz, f., gral. av.   
1                  de los corrales av.   
2                                  NaN   
3             villegas, conrado, gral.   
4              saenz pe?a, luis, pres.   

                               Dirección Normalizada  COMUNA         pos x  \
0  piedra buena av. y fernandez de la cruz, f., g...       8  -58.47533969   
1               paz, gral. av. y de los corrales av.       9  -58.50877521   
2                                entre rios av. 2034       1  -58.39040293   
3          larrazabal av. y villegas, conrado, gral.       8  -58.46503904   
4            san juan av. y saenz peã‘a, luis, pres.       1  -58.38718297   

          pos y VICTIMA_x    ACUSADO        ROL VICTIMA_y       SEXO EDAD  \
0  -34.68757022      moto       auto  conductor      moto  masculino   19   
1  -34.66977709      auto  pasajeros  conductor      auto  masculino   70   
2  -34.63189362      moto       auto  conductor      moto  masculino   30   
3  -34.68092974      moto         sd  conductor      moto  masculino   18   
4  -34.62246630      moto  pasajeros  conductor      moto  masculino   29   

   FECHA_FALLECIMIENTO  
0  2016-01-01 00:00:00  
1  2016-01-02 00:00:00  
2  2016-01-03 00:00:00  
3                   SD  
4  2016-02-01 00:00:00

Verificamos que victima x es igual a victima y

In [22]:
df_hechos_victimas_dif = df_hechos_victimas[df_hechos_victimas['VICTIMA_x'] != df_hechos_victimas['VICTIMA_y']]
df_hechos_victimas_dif

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA HH  \
237  2017-0108           1 2017-09-02    2017     9     2  04:53:08  4   
238  2017-0108           1 2017-09-02    2017     9     2  04:53:08  4   
602  2020-0063           1 2020-12-05    2020    12     5  07:10:00  7   
603  2020-0063           1 2020-12-05    2020    12     5  07:10:00  7   

              LUGAR_DEL_HECHO TIPO_DE_CALLE           Calle        Cruce  \
237   av. gral. paz y machain      gral paz  paz, gral. av.      machain   
238   av. gral. paz y machain      gral paz  paz, gral. av.      machain   
602  nueva york y alta gracia         calle      nueva york  alta gracia   
603  nueva york y alta gracia         calle      nueva york  alta gracia   

        Dirección Normalizada  COMUNA         pos x         pos y  \
237  paz, gral. av. y machain      12  -58.49491054  -34.54795581   
238  paz, gral. av. y machain      12  -58.49491054  -34.54795581   
602  nueva york y alta gracia      11  -58.52783814  -34.61047001   
603  nueva york y alta gracia      11  -58.52783814  -34.61047001   

       VICTIMA_x ACUSADO                    ROL VICTIMA_y       SEXO EDAD  \
237  objeto fijo    auto  pasajero_acompaniante      auto  masculino   17   
238  objeto fijo    auto  pasajero_acompaniante      auto  masculino   10   
602  peaton_moto    moto                 peaton    peaton  masculino   38   
603  peaton_moto    moto  pasajero_acompaniante      moto  masculino   21   

     FECHA_FALLECIMIENTO  
237  2017-09-02 00:00:00  
238  2017-09-02 00:00:00  
602  2020-12-05 00:00:00  
603  2020-12-05 00:00:00

Se puede analizar que objeto_fijo no es parte de victimas por tanto ambas columnas estan volteadas, ademas se puede evidenciar antes que en la columna participantes esta al reves por ese motivo se intercambiara ambos

In [23]:
df_hechos_victimas.at[237, 'ACUSADO'] = df_hechos_victimas.at[237, 'VICTIMA_x']
df_hechos_victimas.at[238, 'ACUSADO'] = df_hechos_victimas.at[238, 'VICTIMA_x']
df_hechos_victimas.at[237, 'VICTIMA_x'] = df_hechos_victimas.at[237, 'VICTIMA_y']
df_hechos_victimas.at[238, 'VICTIMA_x'] = df_hechos_victimas.at[238, 'VICTIMA_y']

Ahora para el indice 603 y 602 esta convinado peaton_moto y esto quiere decir que estan convinado indicando que dos personas murieron, ademas eso dice en n_victimas, sin embargo estos los separamos y por eso pondremos el de victima_y porque ahi muestra separado

In [24]:
df_hechos_victimas.at[602, 'VICTIMA_x'] = df_hechos_victimas.at[602, 'VICTIMA_y']
df_hechos_victimas.at[603, 'VICTIMA_x'] = df_hechos_victimas.at[603, 'VICTIMA_y']

In [25]:
df_hechos_victimas_dif2 = df_hechos_victimas[df_hechos_victimas['VICTIMA_x'] != df_hechos_victimas['VICTIMA_y']]
df_hechos_victimas_dif2

Empty DataFrame
Columns: [idHecho, N_VICTIMAS, FECHA_x, AAAA_x, MM_x, DD_x, HORA, HH, LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle, Cruce, Dirección Normalizada, COMUNA, pos x, pos y, VICTIMA_x, ACUSADO, ROL, VICTIMA_y, SEXO, EDAD, FECHA_FALLECIMIENTO]
Index: []

Ahora se puede ver que ya no tenemos valores diferentes por lo cual podemos pasar a borrar esta columna ya que representan lo mismo y algunas columnas que contienenn muchos nulos

In [26]:
df_hechos_victimas.drop(['LUGAR_DEL_HECHO', 'Calle', 'Cruce', 'Dirección Normalizada', 'FECHA_FALLECIMIENTO', 'VICTIMA_y'], axis=1, inplace=True)
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA HH  \
0  2016-0001           1 2016-01-01    2016     1     1  04:00:00  4   
1  2016-0002           1 2016-01-02    2016     1     2  01:15:00  1   
2  2016-0003           1 2016-01-03    2016     1     3  07:00:00  7   
3  2016-0004           1 2016-01-10    2016     1    10  00:00:00  0   
4  2016-0005           1 2016-01-21    2016     1    21  05:20:00  5   

  TIPO_DE_CALLE  COMUNA         pos x         pos y VICTIMA_x    ACUSADO  \
0       avenida       8  -58.47533969  -34.68757022      moto       auto   
1      gral paz       9  -58.50877521  -34.66977709      auto  pasajeros   
2       avenida       1  -58.39040293  -34.63189362      moto       auto   
3       avenida       8  -58.46503904  -34.68092974      moto         sd   
4       avenida       1  -58.38718297  -34.62246630      moto  pasajeros   

         ROL       SEXO EDAD  
0  conductor  masculino   19  
1  conductor  masculino   70  
2  conductor  masculino   30  
3  conductor  masculino   18  
4  conductor  masculino   29

Las columnas pos x y pos y las cambiamos a Longitud y latitud

In [27]:
# Rename column 'pos x' a 'Longitud'
df_hechos_victimas = df_hechos_victimas.rename(columns={'pos x': 'Longitud'})

# Rename column 'pos y' a 'Latitud'
df_hechos_victimas = df_hechos_victimas.rename(columns={'pos y': 'Latitud'})

Convertimos la longitud y latitud a decimal y los datos faltantes lo ponemos en NaN

In [28]:
# Intentar convertir las columnas 'Latitud' y 'Longitud' a números flotantes con 'errors='coerce''
df_hechos_victimas['Latitud'] = pd.to_numeric(df_hechos_victimas['Latitud'], errors='coerce')
df_hechos_victimas['Longitud'] = pd.to_numeric(df_hechos_victimas['Longitud'], errors='coerce')
df_hechos_victimas

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA  HH  \
0    2016-0001           1 2016-01-01    2016     1     1  04:00:00   4   
1    2016-0002           1 2016-01-02    2016     1     2  01:15:00   1   
2    2016-0003           1 2016-01-03    2016     1     3  07:00:00   7   
3    2016-0004           1 2016-01-10    2016     1    10  00:00:00   0   
4    2016-0005           1 2016-01-21    2016     1    21  05:20:00   5   
..         ...         ...        ...     ...   ...   ...       ...  ..   
712  2021-0093           1 2021-12-13    2021    12    13  17:10:00  17   
713  2021-0094           1 2021-12-20    2021    12    20  01:10:00   1   
714  2021-0095           1 2021-12-30    2021    12    30  00:43:00   0   
715  2021-0096           1 2021-12-15    2021    12    15  10:30:00  10   
716  2021-0097           1 2021-11-18    2021    11    18  06:10:00   6   

    TIPO_DE_CALLE  COMUNA   Longitud    Latitud  VICTIMA_x    ACUSADO  \
0         avenida       8 -58.475340 -34.687570       moto       auto   
1        gral paz       9 -58.508775 -34.669777       auto  pasajeros   
2         avenida       1 -58.390403 -34.631894       moto       auto   
3         avenida       8 -58.465039 -34.680930       moto         sd   
4         avenida       1 -58.387183 -34.622466       moto  pasajeros   
..            ...     ...        ...        ...        ...        ...   
712       avenida       7 -58.433538 -34.645616       moto       auto   
713     autopista       9 -58.467398 -34.651178       moto       auto   
714       avenida      11 -58.472934 -34.619847       moto     cargas   
715       avenida       9 -58.470668 -34.650217       auto     cargas   
716         calle       1 -58.379762 -34.586796  bicicleta       auto   

                       ROL       SEXO EDAD  
0                conductor  masculino   19  
1                conductor  masculino   70  
2                conductor  masculino   30  
3                conductor  masculino   18  
4                conductor  masculino   29  
..                     ...        ...  ...  
712  pasajero_acompaniante   femenino   18  
713  pasajero_acompaniante   femenino   43  
714              conductor  masculino   27  
715              conductor  masculino   60  
716               ciclista  masculino   53  

[717 rows x 17 columns]

Verificamos los valores nan

In [29]:
# Encuentra las filas con valores problemáticos (NaN) en las columnas 'Latitud' o 'Longitud'
filas_con_nan = df_hechos_victimas[(df_hechos_victimas['Latitud'].isna()) | (df_hechos_victimas['Longitud'].isna())]

# Rellena las filas problemáticas con ceros en las columnas 'Latitud' y 'Longitud'
df_hechos_victimas[['Latitud', 'Longitud']] = df_hechos_victimas[['Latitud', 'Longitud']].fillna(0)


Podemos ver una cantidad de valores nan y esto ocurre en ambos y para este problema los rellenamos en 0 para luego filtrarlos al uzarlos en un mapa

### Tratamientos en la columna HH

convertimos los valores a numerico y los errores a nan

In [30]:
# Convertir la columna a números, manejar valores no numéricos asignándoles NaN
df_hechos_victimas['HH'] = pd.to_numeric(df_hechos_victimas['HH'], errors='coerce')

obtenemos los valores que no son nan para ver como rellenar los valores si con la media o mediana y esto dependera al coeficiente de variacion

In [31]:
# Eliminar filas con valores NaN
df_validos = df_hechos_victimas.dropna(subset=['HH'])
# Calcular la media y la desviación estándar de la columna
media = df_validos['HH'].mean()
desviacion_estandar = df_validos['HH'].std()

# Calcular el coeficiente de variación
coeficiente_variacion = (desviacion_estandar / media) * 100
coeficiente_variacion

57.98669510366472

Al ser un valor mayor al 50% se decide usar la mediana por la dispercion de los datos

In [32]:
# Calcular la mediana de la columna
mediana = int(df_hechos_victimas['HH'].median())

# Rellenar NaN con la mediana
df_hechos_victimas['HH'] = df_hechos_victimas['HH'].fillna(mediana)


# Convertir la columna 'HH' a tipo de dato entero
df_hechos_victimas['HH'] = df_hechos_victimas['HH'].astype(int)

Para la columna HORA ponemos esta media ya que tambien es nulo y creamos la funcion para cambiar de formato

In [33]:
def convertir_hora(decimal_hora):
    # Extraer la parte entera y decimal de la hora
    horas_enteras = int(decimal_hora)
    minutos_decimales = (decimal_hora - horas_enteras) * 60

    # Formatear como cadena de tiempo (HH:MM)
    hora_formateada = f"{horas_enteras:02d}:{int(minutos_decimales):02d}"

    return hora_formateada
df_hechos_victimas['HORA'] = df_hechos_victimas['HORA'].replace('SD', convertir_hora(mediana))
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x      HORA  HH  \
0  2016-0001           1 2016-01-01    2016     1     1  04:00:00   4   
1  2016-0002           1 2016-01-02    2016     1     2  01:15:00   1   
2  2016-0003           1 2016-01-03    2016     1     3  07:00:00   7   
3  2016-0004           1 2016-01-10    2016     1    10  00:00:00   0   
4  2016-0005           1 2016-01-21    2016     1    21  05:20:00   5   

  TIPO_DE_CALLE  COMUNA   Longitud    Latitud VICTIMA_x    ACUSADO        ROL  \
0       avenida       8 -58.475340 -34.687570      moto       auto  conductor   
1      gral paz       9 -58.508775 -34.669777      auto  pasajeros  conductor   
2       avenida       1 -58.390403 -34.631894      moto       auto  conductor   
3       avenida       8 -58.465039 -34.680930      moto         sd  conductor   
4       avenida       1 -58.387183 -34.622466      moto  pasajeros  conductor   

        SEXO EDAD  
0  masculino   19  
1  masculino   70  
2  masculino   30  
3  masculino   18  
4  masculino   29

Verificamos ahora si aun tenemos valores nan

In [34]:
# Verificar si hay NaN en la columna
hay_nan = df_hechos_victimas['HH'].isna().any()

# Mostrar el resultado
if hay_nan:
    print('La columna contiene valores NaN.')
else:
    print('La columna no contiene valores NaN.')

La columna no contiene valores NaN.


Creamos una funcion para que los valores sd cambien a nan

In [35]:
def columns_modifier(DF,columns, value, replace=None):
    df=DF.copy()
    
    for index, row in df.iterrows():
        to_replace=row[columns[0]]

        if to_replace == value:
            df.at[index, columns[0]] = replace
    return df

convertimos algunas columnas numericas a nan los valores sd

In [36]:
columna=['HORA']
df_hechos_victimas=columns_modifier(df_hechos_victimas, columna,'sd',np.nan)

In [37]:
columna=['EDAD']
df_hechos_victimas=columns_modifier(df_hechos_victimas, columna,'SD',np.nan)

### Tranformaciones en columna HORA

mostramos las filas de horas con formato diferente 

In [38]:
# Convertir los valores de la columna "hora" a cadenas de texto
df_hechos_victimas['HORA'] = df_hechos_victimas['HORA'].astype(str)

# Verificar si el valor en cada fila tiene un formato de hora válido
formato_correcto = df_hechos_victimas['HORA'].str.match(r'^\d{2}:\d{2}:\d{2}$')

# Filtrar las filas con formato diferente
filas_con_formato_diferente = df_hechos_victimas[~formato_correcto]

# Mostrar las filas con formato diferente
filas_con_formato_diferente

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x  \
457  2019-0022           1 2019-03-15    2019     3    15   
459  2019-0024           1 2019-03-19    2019     3    19   
514  2019-0080           1 2019-09-17    2019     9    17   
536  2019-0103           1 2019-12-18    2019    12    18   

                    HORA  HH TIPO_DE_CALLE  COMUNA   Longitud    Latitud  \
457  1900-01-02 00:00:00   0       avenida       1 -58.391238 -34.623522   
459  1900-01-14 07:12:00   7       avenida       1 -58.372081 -34.585420   
514  1900-01-04 18:40:00  18      gral paz      13 -58.476178 -34.538257   
536                11:00  11      gral paz      11 -58.521694 -34.594716   

    VICTIMA_x ACUSADO                    ROL       SEXO EDAD  
457      auto      sd  pasajero_acompaniante  masculino  NaN  
459      moto  cargas              conductor  masculino   32  
514    peaton    moto                 peaton  masculino   76  
536      moto    moto              conductor  masculino   24

trasformamos a datetime y despues mostraremos si tenemos algun nan

In [39]:
# Convertir los valores de la columna "hora" a objetos de tiempo (datetime)
df_hechos_victimas['HORA'] = pd.to_datetime(df_hechos_victimas['HORA'], errors='coerce')

# Identificar filas con errores de conversión (formato incorrecto)
filas_con_errores = df_hechos_victimas[df_hechos_victimas['HORA'].isna()]

# Mostrar las filas con formato diferente
print("Filas con formato diferente:")
print(filas_con_errores)

Filas con formato diferente:
Empty DataFrame
Columns: [idHecho, N_VICTIMAS, FECHA_x, AAAA_x, MM_x, DD_x, HORA, HH, TIPO_DE_CALLE, COMUNA, Longitud, Latitud, VICTIMA_x, ACUSADO, ROL, SEXO, EDAD]
Index: []


Se puede ver que no tenemos filas con errores

### Transformacion en Edad

In [40]:
# Convierte la columna a entero (ignorando los datos nulos por ahora)
df_hechos_victimas['EDAD'] = pd.to_numeric(df_hechos_victimas['EDAD'], errors='coerce')

# Calcula la mediana de la columna (ignorando los datos nulos)
mediana = df_hechos_victimas['EDAD'].median()

# Rellena los datos nulos con la mediana
df_hechos_victimas['EDAD'].fillna(mediana, inplace=True)

# Convierte la columna a entero nuevamente, asegurándote de que los datos nulos ya han sido reemplazados
df_hechos_victimas['EDAD'] = df_hechos_victimas['EDAD'].astype(int)
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x                HORA  \
0  2016-0001           1 2016-01-01    2016     1     1 2023-12-05 04:00:00   
1  2016-0002           1 2016-01-02    2016     1     2 2023-12-05 01:15:00   
2  2016-0003           1 2016-01-03    2016     1     3 2023-12-05 07:00:00   
3  2016-0004           1 2016-01-10    2016     1    10 2023-12-05 00:00:00   
4  2016-0005           1 2016-01-21    2016     1    21 2023-12-05 05:20:00   

   HH TIPO_DE_CALLE  COMUNA   Longitud    Latitud VICTIMA_x    ACUSADO  \
0   4       avenida       8 -58.475340 -34.687570      moto       auto   
1   1      gral paz       9 -58.508775 -34.669777      auto  pasajeros   
2   7       avenida       1 -58.390403 -34.631894      moto       auto   
3   0       avenida       8 -58.465039 -34.680930      moto         sd   
4   5       avenida       1 -58.387183 -34.622466      moto  pasajeros   

         ROL       SEXO  EDAD  
0  conductor  masculino    19  
1  conductor  masculino    70  
2  conductor  masculino    30  
3  conductor  masculino    18  
4  conductor  masculino    29

In [41]:
df_hechos_victimas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 717 entries, 0 to 716
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   idHecho        717 non-null    object        
 1   N_VICTIMAS     717 non-null    int64         
 2   FECHA_x        717 non-null    datetime64[ns]
 3   AAAA_x         717 non-null    int64         
 4   MM_x           717 non-null    int64         
 5   DD_x           717 non-null    int64         
 6   HORA           717 non-null    datetime64[ns]
 7   HH             717 non-null    int32         
 8   TIPO_DE_CALLE  717 non-null    object        
 9   COMUNA         717 non-null    int64         
 10  Longitud       717 non-null    float64       
 11  Latitud        717 non-null    float64       
 12  VICTIMA_x      717 non-null    object        
 13  ACUSADO        717 non-null    object        
 14  ROL            717 non-null    object        
 15  SEXO           717 non-

## Datos Adicionales Para los Graficos, analisis y kpi

### Columna semestre

Creamos una columna semestre que nos ayudar a una definicion de kpi

In [42]:
# Crear la columna 'semestre'
df_hechos_victimas['semestre'] = df_hechos_victimas['FECHA_x'].dt.month // 7 + 1
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x                HORA  \
0  2016-0001           1 2016-01-01    2016     1     1 2023-12-05 04:00:00   
1  2016-0002           1 2016-01-02    2016     1     2 2023-12-05 01:15:00   
2  2016-0003           1 2016-01-03    2016     1     3 2023-12-05 07:00:00   
3  2016-0004           1 2016-01-10    2016     1    10 2023-12-05 00:00:00   
4  2016-0005           1 2016-01-21    2016     1    21 2023-12-05 05:20:00   

   HH TIPO_DE_CALLE  COMUNA   Longitud    Latitud VICTIMA_x    ACUSADO  \
0   4       avenida       8 -58.475340 -34.687570      moto       auto   
1   1      gral paz       9 -58.508775 -34.669777      auto  pasajeros   
2   7       avenida       1 -58.390403 -34.631894      moto       auto   
3   0       avenida       8 -58.465039 -34.680930      moto         sd   
4   5       avenida       1 -58.387183 -34.622466      moto  pasajeros   

         ROL       SEXO  EDAD  semestre  
0  conductor  masculino    19         1  
1  conductor  masculino    70         1  
2  conductor  masculino    30         1  
3  conductor  masculino    18         1  
4  conductor  masculino    29         1

### Columna dia_semana_espanol

Crearemos la columna dia_semana_espanol para volver cada dia a texto perteneciente al nombre de la semana

In [43]:
# Diccionario de traducción de días de la semana de inglés a español
dias_semana = {
    'Monday': 'Lunes',
    'Tuesday': 'Martes',
    'Wednesday': 'Miércoles',
    'Thursday': 'Jueves',
    'Friday': 'Viernes',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

# Obtén el nombre del día de la semana y crea una nueva columna
df_hechos_victimas['nombre_dia'] = df_hechos_victimas['FECHA_x'].dt.strftime('%A')
df_hechos_victimas

# Change column type to string for column: 'nombre_dia'
df_hechos_victimas = df_hechos_victimas.astype({'nombre_dia': 'string'})
df_hechos_victimas['dia_semana_espanol'] = df_hechos_victimas['nombre_dia'].replace(dias_semana)
df_hechos_victimas.drop(columns=['nombre_dia'], inplace=True)
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x                HORA  \
0  2016-0001           1 2016-01-01    2016     1     1 2023-12-05 04:00:00   
1  2016-0002           1 2016-01-02    2016     1     2 2023-12-05 01:15:00   
2  2016-0003           1 2016-01-03    2016     1     3 2023-12-05 07:00:00   
3  2016-0004           1 2016-01-10    2016     1    10 2023-12-05 00:00:00   
4  2016-0005           1 2016-01-21    2016     1    21 2023-12-05 05:20:00   

   HH TIPO_DE_CALLE  COMUNA   Longitud    Latitud VICTIMA_x    ACUSADO  \
0   4       avenida       8 -58.475340 -34.687570      moto       auto   
1   1      gral paz       9 -58.508775 -34.669777      auto  pasajeros   
2   7       avenida       1 -58.390403 -34.631894      moto       auto   
3   0       avenida       8 -58.465039 -34.680930      moto         sd   
4   5       avenida       1 -58.387183 -34.622466      moto  pasajeros   

         ROL       SEXO  EDAD  semestre dia_semana_espanol  
0  conductor  masculino    19         1            Viernes  
1  conductor  masculino    70         1             Sábado  
2  conductor  masculino    30         1            Domingo  
3  conductor  masculino    18         1            Domingo  
4  conductor  masculino    29         1             Jueves

### Columna Rango etario

Agrupamos la edad en rangos etarios para tener una mejor comprencion de los datos 'Infante', 'Niñez', 'Adolescencia', 'Adulto Joven', 'Adulto', 'Adulto de Edad Media', 'Adulto Mayor', 'Anciano'

In [44]:
# Definir los límites de los rangos etarios
bins = [0, 5, 12, 18, 24, 35, 45, 60, 100]  # Puedes ajustar estos límites según tus necesidades

# Definir las etiquetas para cada rango etario
labels = ['Infante', 'Niñez', 'Adolescencia', 'Adulto Joven', 'Adulto', 'Adulto de Edad Media', 'Adulto Mayor', 'Anciano']

# Crear una nueva columna 'Rango Etario'
df_hechos_victimas['Rango Etario'] = pd.cut(df_hechos_victimas['EDAD'], bins=bins, labels=labels, right=False)
df_hechos_victimas.drop(columns=['EDAD'], inplace=True)
df_hechos_victimas.head()

idHecho  N_VICTIMAS    FECHA_x  AAAA_x  MM_x  DD_x                HORA  \
0  2016-0001           1 2016-01-01    2016     1     1 2023-12-05 04:00:00   
1  2016-0002           1 2016-01-02    2016     1     2 2023-12-05 01:15:00   
2  2016-0003           1 2016-01-03    2016     1     3 2023-12-05 07:00:00   
3  2016-0004           1 2016-01-10    2016     1    10 2023-12-05 00:00:00   
4  2016-0005           1 2016-01-21    2016     1    21 2023-12-05 05:20:00   

   HH TIPO_DE_CALLE  COMUNA   Longitud    Latitud VICTIMA_x    ACUSADO  \
0   4       avenida       8 -58.475340 -34.687570      moto       auto   
1   1      gral paz       9 -58.508775 -34.669777      auto  pasajeros   
2   7       avenida       1 -58.390403 -34.631894      moto       auto   
3   0       avenida       8 -58.465039 -34.680930      moto         sd   
4   5       avenida       1 -58.387183 -34.622466      moto  pasajeros   

         ROL       SEXO  semestre dia_semana_espanol  Rango Etario  
0  conductor  masculino         1            Viernes  Adulto Joven  
1  conductor  masculino         1             Sábado       Anciano  
2  conductor  masculino         1            Domingo        Adulto  
3  conductor  masculino         1            Domingo  Adulto Joven  
4  conductor  masculino         1             Jueves        Adulto

### Exportacion de datos

In [ ]:
df_hechos_victimas.to_csv('Dataset/df_hechos_victimas_clean_t.csv', index=False)